package com.tooqy.football_api.Model

import com.google.gson.annotations.SerializedName

data class SearchEvent(
        @SerializedName("idEvent") val idEvent: String,
        @SerializedName("idSoccerXML") val idSoccerXML: String,
        @SerializedName("strEvent") val strEvent: String,
        @SerializedName("strFilename") val strFilename: String,
        @SerializedName("strSport") val strSport: String,
        @SerializedName("idLeague") val idLeague: String,
        @SerializedName("strLeague") val strLeague: String,
        @SerializedName("strSeason") val strSeason: String,
        @SerializedName("strDescriptionEN") val strDescriptionEN: Any,
        @SerializedName("strHomeTeam") val strHomeTeam: String,
        @SerializedName("strAwayTeam") val strAwayTeam: String,
        @SerializedName("intHomeScore") val intHomeScore: String,
        @SerializedName("intRound") val intRound: String,
        @SerializedName("intAwayScore") val intAwayScore: String,
        @SerializedName("intSpectators") val intSpectators: Any,
        @SerializedName("strHomeGoalDetails") val strHomeGoalDetails: Any,
        @SerializedName("strHomeRedCards") val strHomeRedCards: Any,
        @SerializedName("strHomeYellowCards") val strHomeYellowCards: Any,
        @SerializedName("strHomeLineupGoalkeeper") val strHomeLineupGoalkeeper: Any,
        @SerializedName("strHomeLineupDefense") val strHomeLineupDefense: Any,
        @SerializedName("strHomeLineupMidfield") val strHomeLineupMidfield: Any,
        @SerializedName("strHomeLineupForward") val strHomeLineupForward: Any,
        @SerializedName("strHomeLineupSubstitutes") val strHomeLineupSubstitutes: Any,
        @SerializedName("strHomeFormation") val strHomeFormation: Any,
        @SerializedName("strAwayRedCards") val strAwayRedCards: Any,
        @SerializedName("strAwayYellowCards") val strAwayYellowCards: Any,
        @SerializedName("strAwayGoalDetails") val strAwayGoalDetails: Any,
        @SerializedName("strAwayLineupGoalkeeper") val strAwayLineupGoalkeeper: Any,
        @SerializedName("strAwayLineupDefense") val strAwayLineupDefense: Any,
        @SerializedName("strAwayLineupMidfield") val strAwayLineupMidfield: Any,
        @SerializedName("strAwayLineupForward") val strAwayLineupForward: Any,
        @SerializedName("strAwayLineupSubstitutes") val strAwayLineupSubstitutes: Any,
        @SerializedName("strAwayFormation") val strAwayFormation: Any,
        @SerializedName("intHomeShots") val intHomeShots: Any,
        @SerializedName("intAwayShots") val intAwayShots: Any,
        @SerializedName("dateEvent") val dateEvent: String,
        @SerializedName("strDate") val strDate: String,
        @SerializedName("strTime") val strTime: String,
        @SerializedName("strTVStation") val strTVStation: Any,
        @SerializedName("idHomeTeam") val idHomeTeam: String,
        @SerializedName("idAwayTeam") val idAwayTeam: String,
        @SerializedName("strResult") val strResult: Any,
        @SerializedName("strCircuit") val strCircuit: Any,
        @SerializedName("strCountry") val strCountry: Any,
        @SerializedName("strCity") val strCity: Any,
        @SerializedName("strPoster") val strPoster: Any,
        @SerializedName("strFanart") val strFanart: Any,
        @SerializedName("strThumb") val strThumb: Any,
        @SerializedName("strBanner") val strBanner: Any,
        @SerializedName("strMap") val strMap: Any,
        @SerializedName("strLocked") val strLocked: String
)